export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_ADD_TO_PEOPLE_REQUEST = 'USER_ADD_TO_PEOPLE_REQUEST'
export const USER_ADD_TO_PEOPLE_SUCCESS = 'USER_ADD_TO_PEOPLE_SUCCESS'
export const USER_ADD_TO_PEOPLE_FAIL = 'USER_ADD_TO_PEOPLE_FAIL'
export const USER_ADD_TO_PEOPLE_DELETE = 'USER_ADD_TO_PEOPLE_DELETE'

export const USER_LOGOUT = 'USER_LOGOUT'

export const GET_BALANCE_REQUEST = 'GET_BALANCE_REQUEST'
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS'
export const GET_BALANCE_FAIL = 'GET_BALANCE_FAIL'

export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST'
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS'
export const GET_TRANSACTIONS_FAIL = 'GET_TRANSACTIONS_FAIL'

export const CREATE_TRANSACTION_REQUEST = 'CREATE_TRANSACTION_REQUEST'
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS'
export const CREATE_TRANSACTION_FAIL = 'CREATE_TRANSACTION_FAIL'
export const CREATE_TRANSACTION_DELETE = 'CREATE_TRANSACTION_DELETE'

export const GET_PEOPLE_REQUEST = 'GET_PEOPLE_REQUEST'
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS'
export const GET_PEOPLE_FAIL = 'GET_PEOPLE_FAIL'

export const GET_PERSON_REQUEST = 'GET_PERSON_REQUEST'
export const GET_PERSON_SUCCESS = 'GET_PERSON_SUCCESS'
export const GET_PERSON_FAIL = 'GET_PERSON_FAIL'

export const PASSWORD_CHANGE_REQUEST = 'PASSWORD_CHANGE_REQUEST'
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS'
export const PASSWORD_CHANGE_FAIL = 'PASSWORD_CHANGE_FAIL'
export const PASSWORD_CHANGE_DELETE = 'PASSWORD_CHANGE_DELETE'
